# https://backstage.io/docs/features/software-catalog/descriptor-format#kind-user
apiVersion: backstage.io/v1alpha1
kind: User
metadata:
  name: camila-rodrigues
  title: Product Owner — IDP e Gerador
spec:
  profile:
    displayName: Camila Rodrigues
    email: camila.rodrigues@produto.interno
  memberOf:
    - group:default/squad-gerador-scaffolding
