# https://backstage.io/docs/features/software-catalog/descriptor-format#kind-user
apiVersion: backstage.io/v1alpha1
kind: User
metadata:
  name: eduardo-de-lucca
  title: Software Engineer — Gerador
spec:
  profile:
    displayName: Eduardo de Lucca
    email: eduardo@idp.interno
  memberOf:
    - group:default/squad-gerador-scaffolding
