# https://backstage.io/docs/features/software-catalog/descriptor-format#kind-user
apiVersion: backstage.io/v1alpha1
kind: User
metadata:
  name: felipe-amaral
  title: SRE — observabilidade e confiabilidade
spec:
  profile:
    displayName: Felipe Amaral
    email: felipe.amaral@sre.interno
  memberOf:
    - group:default/squad-observabilidade-sre
