# https://backstage.io/docs/features/software-catalog/descriptor-format#kind-user
apiVersion: backstage.io/v1alpha1
kind: User
metadata:
  name: lucas-figueiredo
  title: ML Engineer — Super-RAG / SUPERAG
spec:
  profile:
    displayName: Lucas Figueiredo
    email: lucas.figueiredo@ia.interno
  memberOf:
    - group:default/squad-super-rag
