# https://backstage.io/docs/features/software-catalog/descriptor-format#kind-user
apiVersion: backstage.io/v1alpha1
kind: User
metadata:
  name: lucas-palhares-barbosa
  title: Tech Lead — Gerador de Scaffolding
spec:
  profile:
    displayName: Lucas Palhares Barbosa
    email: lucas.palahres@idp.interno
  memberOf:
    - group:default/squad-gerador-scaffolding
