# https://backstage.io/docs/features/software-catalog/descriptor-format#kind-user
apiVersion: backstage.io/v1alpha1
kind: User
metadata:
  name: ricardo-vieira
  title: Arquiteto de Software — padrões e esteiras
spec:
  profile:
    displayName: Ricardo Vieira
    email: ricardo.vieira@arquitetura.interno
  memberOf:
    - group:default/squad-arquitetura
