# https://backstage.io/docs/features/software-catalog/descriptor-format#kind-system
apiVersion: backstage.io/v1alpha1
kind: System
metadata:
  name: esteiras-cicd-claro
  title: Esteiras CI/CD Claro
  description: >-
    Esteiras Digital/TI e GitOps agnóstico — pipelines, promoção entre
    ambientes e padrões de entrega contínua.
spec:
  owner: group:default/squad-arquitetura
  domain: domain:default/claro-digital-engenharia
