# https://backstage.io/docs/features/software-catalog/descriptor-format#kind-system
apiVersion: backstage.io/v1alpha1
kind: System
metadata:
  name: gerador-scaffolding
  title: Gerador de Scaffolding
  description: >-
    Produto Gerador de Scaffolding — visão fim a fim (templates, fluxos,
    integrações e entrega para squads consumidores).
spec:
  owner: group:default/squad-gerador-scaffolding
  domain: domain:default/claro-idp
