# https://backstage.io/docs/features/software-catalog/descriptor-format#kind-group
apiVersion: backstage.io/v1alpha1
kind: Group
metadata:
  name: squad-seguranca
  title: Squad Segurança
  description: Time de segurança da informação, políticas e revisão de superfícies de ataque.
spec:
  type: team
  children: []
