# https://backstage.io/docs/features/software-catalog/descriptor-format#kind-group
apiVersion: backstage.io/v1alpha1
kind: Group
metadata:
  name: squad-arquitetura
  title: Squad Arquitetura
  description: Time de arquitetura corporativa, padrões e fronteiras de sistemas.
spec:
  type: team
  children: []
