# https://backstage.io/docs/features/software-catalog/descriptor-format#kind-group
apiVersion: backstage.io/v1alpha1
kind: Group
metadata:
  name: squad-super-rag
  title: Squad SuperRag
  description: Time Superag focado na implementação e sustentação da SuperRag.
spec:
  type: team
  children: []
