# https://backstage.io/docs/features/software-catalog/descriptor-format#kind-component
apiVersion: backstage.io/v1alpha1
kind: Component
metadata:
  name: cicd-gitlab-adapter
  title: CI/CD — adaptador GitLab
  description: >-
    Adaptador GitLab (evolução) para integração com pipelines e repositórios
    corporativos.
spec:
  type: library
  lifecycle: production
  owner: group:default/squad-gerador-scaffolding
  system: system:default/gerador-scaffolding
