# https://backstage.io/docs/features/software-catalog/descriptor-format#kind-component
apiVersion: backstage.io/v1alpha1
kind: Component
metadata:
  name: e2e-tests-gerador-scaffolding
  title: E2E tests — Gerador
  description: >-
    Suíte de testes ponta a ponta da plataforma Gerador de Scaffolding.
spec:
  type: library
  lifecycle: production
  owner: group:default/squad-gerador-scaffolding
  system: system:default/gerador-scaffolding
