# https://backstage.io/docs/features/software-catalog/descriptor-format#kind-component
apiVersion: backstage.io/v1alpha1
kind: Component
metadata:
  name: golden-image-pipeline-ti
  title: Golden image pipeline — TI
  description: >-
    Pipeline TI — hardening de imagem, scan de vulnerabilidades e assinatura
    para promoção controlada.
spec:
  type: library
  lifecycle: production
  owner: group:default/squad-arquitetura
  system: system:default/esteiras-cicd-claro
