# https://backstage.io/docs/features/software-catalog/descriptor-format#kind-component
apiVersion: backstage.io/v1alpha1
kind: Component
metadata:
  name: sbom-pipeline-gerador
  title: SBOM pipeline — Gerador
  description: >-
    Pipeline de geração e publicação de SBOM para imagens e artefactos do Gerador.
spec:
  type: library
  lifecycle: production
  owner: group:default/squad-gerador-scaffolding
  system: system:default/gerador-scaffolding
