# https://backstage.io/docs/features/software-catalog/descriptor-format#kind-component
apiVersion: backstage.io/v1alpha1
kind: Component
metadata:
  name: superag-client
  title: SUPERAG client
  description: >-
    Cliente HTTP resiliente para integração com as APIs do SUPERAG.
spec:
  type: library
  lifecycle: production
  owner: group:default/squad-gerador-scaffolding
  system: system:default/gerador-scaffolding
